import seaborn as sns
#sns.set_style("white")
import matplotlib.pyplot as plt
import pandas as pd
data1 = pd.read_csv('10_minute_twitter.csv',index_col='Unnamed: 0')
data2 = pd.read_csv('1_hour_twitter.csv',index_col='Unnamed: 0')
plt.figure(figsize = (10, 4))
ax1 = plt.subplot(121)
ax1.plot(data1['g'],color ='firebrick')
ax1.plot(data1['d'],color ='dimgray')
ax1.plot(data1['g1'],color ='firebrick',linestyle='--')
ax1.plot(data1['d1'],color ='dimgray',linestyle='--')
ax1.set_xlabel('epoch',fontsize=14)
ax1.set_ylabel('MAPE',fontsize=12)
ax1.set_title("10 Minutes Observation",fontsize=15)
ax2 = plt.subplot(122)
ax2.plot(data2['g'],color ='firebrick')
ax2.plot(data2['d'],color ='dimgray')
ax2.plot(data2['g1'],color ='firebrick',linestyle='--')
ax2.plot(data2['d1'],color ='dimgray',linestyle='--')
ax2.set_xlabel('epoch',fontsize=14)
ax2.set_ylabel('MAPE',fontsize=12)
ax2.set_title("1 Hour Observation",fontsize=15)
ax1.legend(labels = ['PreNets-MB', 'PreNets-MF','PP-MB','PP-MF'], loc = 'best')
ax2.legend(labels = ['PreNets-MB', 'PreNets-MF','PP-MB','PP-MF'], loc = 'best')
plt.tight_layout(pad=1)
plt.show()